extends: airbnb
parser: babel-eslint
rules:
  semi:
    - 2
    - never
  curly:
    - 2
    - all
  brace-style:
    - 2
    - 1tbs
  react/prefer-stateless-function:
    - 1
    - ignorePureComponents: true
  jsx-a11y/no-static-element-interactions: 0
  react/jsx-space-before-closing:
    - 2
    - never
  react/jsx-tag-spacing:
    - 2
    - beforeSelfClosing: never

env:
  browser: true
  node: true
plugins:
  - react
  - jsx-a11y
  - import
