extends: airbnb
parser: babel-eslint
rules:
  semi: 2
  react/prefer-stateless-function:
    - 1
    - ignorePureComponents: true
  jsx-a11y/no-static-element-interactions: 0
  curly: 2
  brace-style: 2
env:
  browser: true
  node: true
plugins:
  - react
  - jsx-a11y
  - import
