version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/src
    steps:
      - checkout
      - attach_workspace:
          at: ~/src
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Prepare Dependencies
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn greenkeeper-lockfile-update
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            yarn test
      - run:
          name: Test Build
          command: |
            yarn run build
      - run: yarn greenkeeper-lockfile-upload
      - run:
          name: Update Coverage
          command: |
            ./cc-test-reporter after-build --exit-code $?
            cat coverage/lcov.info | ./node_modules/.bin/coveralls
